baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Euphoric Reveries'
theme = 'gallery'
copyright = "© Euphoric Reveries Photography"

[caches]
  [caches.images]
    dir = ':cacheDir/images'