baseURL = 'http://royaire.com'
languageCode = 'en-us'
title = 'Royaire Photography'
theme = 'gallery'
copyright = "© Royaire Photography"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params.imageProcessing]
  cover.enabled=false
  content.enabled=false